[workspace]
authors = ["Vincent Tinet <vincenttinet@mac.com"]
name = "urbantransit"
channels = ["https://prefix.dev/conda-forge", "https://prefix.dev/urbandev"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[tasks]
run = "python -m urbantransit"
package = "python -m build"

[dependencies]
python = ">=3.14.4,<3.15"
pip = ">=25.0,<26"
pandas = ">=3.0.2,<4"
geopandas = ">=1.1.3,<2"
pyarrow = ">=23.0.1,<24"
scikit-learn = ">=1.8.0,<2"
listandstruct = ">=0.0.2,<0.0.3"

[pypi-dependencies]
urbantransit = { path = ".", editable = true }
ruff = ">=0.15.10, <0.16"
build = ">=1.2.2, <2"

[package] 
name = "urbantransit"
version = "0.1.0"

[package.host-dependencies]
hatchling = "*"

[package.build]
backend = { name = "pixi-build-python", version = "*" }