[project]
name = "urbantransit"
description = "Transform and analyse gtfs in a parquet format"
license = "MIT"
version = "0.2.4"
readme = "README.md"
authors = [{name = "chourmo", email = "vincenttinet@icloud.com"}]
requires-python = ">= 3.11"
dependencies = ["pandas", "geopandas", "pyarrow", "scikit-learn"]

[tool.pixi.workspace]
channels = ["conda-forge", "https://prefix.dev/urbandev"]
platforms = ["win-64", "linux-64", "osx-arm64"]
preview = ["pixi-build"]

[tool.pixi.pypi-dependencies]
urbantransit = { path = ".", editable = true }

[tool.pixi.dependencies]
pandas = ">=3.0.5,<4"
geopandas = ">=1.1.4,<2"
pyarrow = ">=25.0.0,<26"
scikit-learn = ">=1.9.0,<2"
listandstruct = ">=0.4.11,<0.5"
geometryhelpers = ">=0.4.3,<0.5"

[tool.pixi.package] 
name = "urbantransit"
version = "0.2.4"

[tool.pixi.package.build] 
backend = { name = "pixi-build-python", version = "0.*" }

[tool.pixi.package.host-dependencies] 
hatchling = "==1.26.3"

[tool.pixi.tasks]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
